# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "069d96c1154dc812ea9a01117cc18ed6"
name = "startstorez AI Chatbot"
handle = "startstorez-chatbot"
application_url = "https://chatbot.startstorez.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://chatbot.startstorez.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://chatbot.startstorez.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/delete", "products/update" ]
  uri = "https://chatbot.startstorez.com/api/webhooks"

  [[webhooks.subscriptions]]
  uri = "https://chatbot.startstorez.com/webhooks"
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://chatbot.startstorez.com/api/auth",
  "https://chatbot.startstorez.com/"
]
